USE RisolKasir;
GO

EXEC sp_rename 'kategori_produk', 'KategoriProduk';
GO

EXEC sp_rename 'KategoriProduk.nama_kategori', 'nama', 'COLUMN';
GO

EXEC sp_rename 'produk.kode_produk', 'kode', 'COLUMN';
EXEC sp_rename 'produk.nama_produk', 'nama', 'COLUMN';
GO

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME='produk' AND COLUMN_NAME='aktif'
)
BEGIN
    ALTER TABLE produk ADD aktif BIT DEFAULT 1 NOT NULL;
    UPDATE produk SET aktif = 1;
END
GO

EXEC sp_rename 'detail_transaksi', 'DetailTransaksi';
GO

SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'DetailTransaksi';
GO

SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'transaksi';
GO

USE RisolKasir;
GO

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE';
GO

SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'kategori_produk';
GO

SELECT * FROM kategori_produk;
GO

USE RisolKasir;
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE';

USE RisolKasir;
SELECT * FROM KategoriProduk;

USE RisolKasir;
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'produk';

USE RisolKasir;
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'transaksi';
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DetailTransaksi';



USE RisolKasir;
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'transaksi' ORDER BY ORDINAL_POSITION;